---
name: Lint and test

on:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'README.md'

jobs:
  action-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color

  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: npm run lint
        run: npm run lint
      - name: npm run type-check
        run: npm run type-check
      - name: npm run test
        run: npm run test
      - name: npm run build
        run: npm run build
