name: 'PR Summarizer'
description: 'Automatically generates and updates pull request descriptions using AI (OpenAI/Anthropic)'
author: 'Meido AI'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  openai-api-key:
    description: 'OpenAI API key for GPT-4'
    required: false
  anthropic-api-key:
    description: 'Anthropic API key for Claude'
    required: false
  model-provider:
    description: 'AI model provider to use (openai or anthropic)'
    required: false
    default: 'openai'
  model:
    description: 'Model to use (e.g., gpt-4 for OpenAI or claude-3-sonnet-20240229 for Anthropic)'
    required: false
    default: 'gpt-4'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'edit-3'
  color: 'blue'
